apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{ include "sampleapp.svclabel" . }}
spec:
  selector:
    app: {{ .Release.Name | quote }}
      #type: LoadBalancer
  type: ClusterIP
  ports:
    - name: appport
      port: 8080
      targetPort: 8080
